branches:
  only:
    - legacy-stable
    - master
    - unstable

language: php

php:
  - 7.1
  - 7.2
  - nightly

stages:
  - lint
  - test

cache:
  directories:
    - $HOME/.composer/cache/files

script:
  - SYMFONY_DEPRECATIONS_HELPER=weak_vendors SYMFONY_PHPUNIT_VERSION=6.5 vendor/bin/simple-phpunit

install:
  - |
      if [ "$SYMFONY_VERSION" != "" ]
      then composer require "symfony/symfony:$SYMFONY_VERSION" --no-update
      fi
  - composer update ${COMPOSER_OPTIONS} --prefer-dist

jobs:
  include:
    - stage: lint
      php: 7.2
      install:
        - wget https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v2.8.3/php-cs-fixer.phar -O php-cs-fixer
        - chmod +x php-cs-fixer
      script:
        - ./php-cs-fixer fix --dry-run --diff
        - composer validate
    - stage: test
    - php: 7.1
      env: COMPOSER_OPTIONS="--prefer-lowest"
    - php: 7.2
      env: SYMFONY_VERSION=3.3.*
    - php: 7.2
      env: SYMFONY_VERSION=3.4
    - php: 7.2
      env: SYMFONY_VERSION=4.1.*@dev
  allow_failures:
    - php: nightly
    - env: SYMFONY_VERSION=4.1.*@dev
